// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9sBLgEYNzQzax7VMpEcO8Ba55feyd_A',
    appId: '1:1057670234257:web:14b6efafb2011dfcb2ff30',
    messagingSenderId: '1057670234257',
    projectId: 'bootcamp-capstone-app',
    authDomain: 'bootcamp-capstone-app.firebaseapp.com',
    storageBucket: 'bootcamp-capstone-app.firebasestorage.app',
    measurementId: 'G-5BYVJCBHYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzNWGbi8ZCa41ejFsgXn9C04wn-z8PAE',
    appId: '1:1057670234257:android:cbe0626338c65813b2ff30',
    messagingSenderId: '1057670234257',
    projectId: 'bootcamp-capstone-app',
    storageBucket: 'bootcamp-capstone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3mH110efidvSR4ch6XYQ_t7OGh4lmNw',
    appId: '1:1057670234257:ios:1db54d9c3eda70c0b2ff30',
    messagingSenderId: '1057670234257',
    projectId: 'bootcamp-capstone-app',
    storageBucket: 'bootcamp-capstone-app.firebasestorage.app',
    iosBundleId: 'com.example.capstoneApp',
  );
}
